name: Test

on: push

permissions:
  packages: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Setup npmrc
        run: ./setup.sh
        env:
          GITHUB_PKG_TOKEN: ${{ secrets.NPM_GITHUB_PKG_TOKEN }}

      - name: Install
        run: yarn install

      - name: Test
        run: yarn start
